### ISSUE TITLE
Just wanted to thank you

### ISSUE THREAD

**Issue by Artaud** [iva2k/ionic4-feathersjsplus-starter#1]
Hey @iva2k, just wanted to say thanks for this and the ionic3 repos. I've been able to get up and running with my ionic4/feathers app from scratch using your steps and the source in about two hours yesterday and I'm sure I'd never be able to do that if it weren't for your guidance.

**Comment by iva2k** [comment]
Glad to see it's useful. Thanks!
BTW, this ionic4 starter app is not completed yet, WIP in this repo.
